### ISSUE TITLE
An UnicodeDecodeError error occurred when I used the 'capture=True' of local function

### ISSUE THREAD

**Issue by ViCrack** [ploxiln/fab-classic#45]
```
fab --version
                                                        
fab-classic 1.18.0
paramiko-ng 2.8.2
Python 3.7.0

```

The python code
`outstr = local('mvn clean package',capture=True)`

Actually the execute result  did not have 'UTF-8' encoding.

output
```
[localhost] local: mvn clean package
Traceback (most recent call last):
  File "d:\Code\fabfile.py", line 130, in <module>
    outstr =local('mvn clean package',capture=True)
  File "D:\Programs\Python37\lib\site-packages\fabric\operations.py", line 1212, in local
    out = _AttributeString(stdout.decode('utf-8').strip() if stdout else "")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbf in position 1480: invalid start byte
```

Can you add an encoding parameter in the local function?

thks

**Comment by ploxiln** [comment]
Yeah, that's pretty easy, we could just add this:

```diff
--- a/fabric/operations.py
+++ b/fabric/operations.py
@@ -1122,7 +1122,7 @@ def sudo(command, shell=True, pty=True, combine_stderr=None, user=None,
     )
 
 
-def local(command, capture=False, shell=None, pty=True):
+def local(command, capture=False, shell=None, pty=True, encoding='utf-8'):
     """
     Run a command on the local system.
 
@@ -1209,8 +1209,8 @@ def local(command, capture=False, shell=None, pty=True):
             dev_null.close()
     # Handle error condition (deal with stdout being None, too)
     if six.PY3:
-        out = _AttributeString(stdout.decode('utf-8').strip() if stdout else "")
-        err = _AttributeString(stderr.decode('utf-8').strip() if stderr else "")
+        out = _AttributeString(stdout.decode(encoding).strip() if stdout else "")
+        err = _AttributeString(stderr.decode(encoding).strip() if stderr else "")
     else:
         out = _AttributeString(stdout.strip() if stdout else "")
         err = _AttributeString(stderr.strip() if stderr else "")
```

but I wonder if there's a better way, to detect the "system standard encoding" automatically? Maybe like this:

```python
--- a/fabric/operations.py
+++ b/fabric/operations.py
@@ -1209,8 +1209,9 @@ def local(command, capture=False, shell=None, pty=True):
             dev_null.close()
     # Handle error condition (deal with stdout being None, too)
     if six.PY3:
-        out = _AttributeString(stdout.decode('utf-8').strip() if stdout else "")
-        err = _AttributeString(stderr.decode('utf-8').strip() if stderr else "")
+        enc = sys.stdout.encoding
+        out = _AttributeString(stdout.decode(enc).strip() if stdout else "")
+        err = _AttributeString(stderr.decode(enc).strip() if stderr else "")
     else:
         out = _AttributeString(stdout.strip() if stdout else "")
         err = _AttributeString(stderr.strip() if stderr else "")
```

**Comment by ViCrack** [comment]
Thank you for your reply.

Using "sys.stdout.encoding" doesn't work for me either.


my test code
```
    if six.PY3:
        out = _AttributeString(stdout.decode(sys.stdout.encoding).strip() if stdout else "")
        err = _AttributeString(stderr.decode(sys.stdout.encoding).strip() if stderr else "")
```
```
    import sys
    print(sys.stdout.encoding)
    out = local('echo 测试', capture=True)
    print(out)
```

output
```
utf-8
[localhost] local: echo 测试
Traceback (most recent call last):
  File "d:\Code\fabfile.py", line 136, in <module>
    out = local('echo 测试', capture=True)
  File "D:\Programs\Python37\lib\site-packages\fabric\operations.py", line 1212, in local
    out = _AttributeString(stdout.decode(sys.stdout.encoding).strip() if stdout else "")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 0: invalid start byte 

```

But
`out = _AttributeString(stdout.decode('GBK').strip() if stdout else "")`
it works.

**Comment by ploxiln** [comment]
you could try https://github.com/ploxiln/fab-classic/pull/47

**Comment by ViCrack** [comment]
nice work
